services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - database
    ports:
      - 9000:8080
    expose:
      - 8080
    volumes:
      - ./:/app

  database:
    image: bitnami/postgresql
    restart: always
    container_name: ${DATABASE_HOST}
    env_file: ".env"
    ports:
      - "5454:5432"
    expose:
      - 5432
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
    volumes:
      - db_data:/bitnami/postgresql
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql

volumes:
  db_data: